<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mahesh-PC" name="com.flipkart.testCases.F_BaseTest" tests="1" failures="0" timestamp="14 Jul 2016 06:50:17 GMT" time="0.000" errors="1">
  <testcase name="setUp" time="0.000" classname="com.flipkart.testCases.F_BaseTest">
    <error type="org.testng.TestNGException" message="
Method public void com.flipkart.testCases.F_BaseTest.setUp(java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : readData1">
      <![CDATA[org.testng.TestNGException: 
Method public void com.flipkart.testCases.F_BaseTest.setUp(java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : readData1
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- setUp -->
</testsuite> <!-- com.flipkart.testCases.F_BaseTest -->
